// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: service_simple_bank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimpleBankService_CreateOwner_FullMethodName = "/pb.SimpleBankService/CreateOwner"
	SimpleBankService_LoginOwner_FullMethodName  = "/pb.SimpleBankService/LoginOwner"
)

// SimpleBankServiceClient is the client API for SimpleBankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleBankServiceClient interface {
	CreateOwner(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginOwner(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type simpleBankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleBankServiceClient(cc grpc.ClientConnInterface) SimpleBankServiceClient {
	return &simpleBankServiceClient{cc}
}

func (c *simpleBankServiceClient) CreateOwner(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, SimpleBankService_CreateOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleBankServiceClient) LoginOwner(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, SimpleBankService_LoginOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleBankServiceServer is the server API for SimpleBankService service.
// All implementations must embed UnimplementedSimpleBankServiceServer
// for forward compatibility.
type SimpleBankServiceServer interface {
	CreateOwner(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginOwner(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedSimpleBankServiceServer()
}

// UnimplementedSimpleBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimpleBankServiceServer struct{}

func (UnimplementedSimpleBankServiceServer) CreateOwner(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOwner not implemented")
}
func (UnimplementedSimpleBankServiceServer) LoginOwner(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginOwner not implemented")
}
func (UnimplementedSimpleBankServiceServer) mustEmbedUnimplementedSimpleBankServiceServer() {}
func (UnimplementedSimpleBankServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimpleBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleBankServiceServer will
// result in compilation errors.
type UnsafeSimpleBankServiceServer interface {
	mustEmbedUnimplementedSimpleBankServiceServer()
}

func RegisterSimpleBankServiceServer(s grpc.ServiceRegistrar, srv SimpleBankServiceServer) {
	// If the following call panics, it indicates UnimplementedSimpleBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimpleBankService_ServiceDesc, srv)
}

func _SimpleBankService_CreateOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleBankServiceServer).CreateOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleBankService_CreateOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleBankServiceServer).CreateOwner(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleBankService_LoginOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleBankServiceServer).LoginOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleBankService_LoginOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleBankServiceServer).LoginOwner(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleBankService_ServiceDesc is the grpc.ServiceDesc for SimpleBankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleBankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SimpleBankService",
	HandlerType: (*SimpleBankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOwner",
			Handler:    _SimpleBankService_CreateOwner_Handler,
		},
		{
			MethodName: "LoginOwner",
			Handler:    _SimpleBankService_LoginOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_simple_bank.proto",
}
